#!/usr/bin/env bash
#
# ripgrep Feature Installation Script
# Installs ripgrep (rg) via devbox global and configures theming
#

set -e

# Source common utilities from system-wide installation
# The lib feature must be installed before this feature
# shellcheck source=/usr/local/lib/devcontainer-features/common.sh
source /usr/local/lib/devcontainer-features/common.sh

# Feature options (passed as environment variables from devcontainer)
VERSION="${VERSION:-latest}"
THEME="${THEME:-db2-dark}"
SMARTCASE="${SMARTCASE:-true}"
ENABLEALIASES="${ENABLEALIASES:-true}"

#######################################
# Install ripgrep via devbox global
#######################################
install_ripgrep() {
    log_info "Installing ripgrep (version: $VERSION)"

    local package_spec="ripgrep"
    if [ "$VERSION" != "latest" ]; then
        package_spec="ripgrep@${VERSION}"
    fi

    devbox_global_add "$package_spec"

    # Verify installation
    if ! command_exists rg; then
        log_error "ripgrep installation failed - command not found"
        exit 1
    fi

    local installed_version
    installed_version=$(rg --version | head -n1)
    log_success "ripgrep installed: $installed_version"
}

#######################################
# Setup theme files to system location
# Copies themes from feature directory to /usr/local/share
#######################################
setup_themes() {
    local themes_src="themes"
    local themes_dest="/usr/local/share/devcontainer-features/ripgrep/themes"

    if [ -d "$themes_src" ]; then
        log_info "Installing ripgrep themes to $themes_dest"
        mkdir -p "$themes_dest"
        cp -r "$themes_src"/* "$themes_dest/"
        local theme_count
        theme_count=$(find "$themes_src" -maxdepth 1 -type f -name "*.theme" | wc -l)
        log_success "Installed $theme_count theme files"
    else
        log_warning "Themes directory not found, skipping theme installation"
    fi
}

#######################################
# Get ripgrep color arguments for a theme
# Reads from theme file and returns color arguments
#######################################
get_theme_colors() {
    local theme="$1"
    local themes_dir="/usr/local/share/devcontainer-features/ripgrep/themes"
    local theme_file="${themes_dir}/${theme}.theme"

    if [ "$theme" = "none" ]; then
        echo ""
        return
    fi

    if [ ! -f "$theme_file" ]; then
        log_warning "Theme file not found: $theme_file, using db2-dark as fallback"
        theme_file="${themes_dir}/db2-dark.theme"
    fi

    if [ -f "$theme_file" ]; then
        # Read theme file, skip comments and empty lines
        # Convert "path:fg:#4A90C8" to "--colors=path:fg:#4A90C8"
        local colors=""
        while IFS= read -r line; do
            # Skip comments and empty lines
            [[ "$line" =~ ^#.*$ ]] && continue
            [[ -z "$line" ]] && continue
            if [ -n "$colors" ]; then
                colors="$colors --colors=$line"
            else
                colors="--colors=$line"
            fi
        done < "$theme_file"
        echo "$colors"
    else
        echo ""
    fi
}

#######################################
# Setup ripgrep configuration
# Creates config file with theme and options
#######################################
setup_config() {
    local user_home
    user_home=$(get_remote_user_home)
    local config_dir="${user_home}/.config/ripgrep"
    local config_file="${config_dir}/config"

    log_info "Setting up ripgrep configuration"

    ensure_directory "$config_dir"

    # Start building config content
    local config_content="# ripgrep configuration
# Generated by devcontainer-features/ripgrep
"

    # Add smart case if enabled
    if [ "$SMARTCASE" = "true" ]; then
        config_content+="
# Smart case: case-insensitive unless uppercase is used
--smart-case"
    fi

    # Add theme colors
    if [ "$THEME" != "none" ]; then
        local themes_dir="/usr/local/share/devcontainer-features/ripgrep/themes"
        local theme_file="${themes_dir}/${THEME}.theme"

        if [ -f "$theme_file" ]; then
            config_content+="

# Theme: ${THEME}"
            while IFS= read -r line; do
                # Skip comments and empty lines
                [[ "$line" =~ ^#.*$ ]] && continue
                [[ -z "$line" ]] && continue
                config_content+="
--colors=$line"
            done < "$theme_file"
        fi
    fi

    # Write config file
    echo "$config_content" > "$config_file"

    # Fix ownership
    local remote_user
    remote_user=$(get_remote_user)
    chown -R "${remote_user}:${remote_user}" "$config_dir"

    log_success "Created ripgrep config at $config_file"
}

#######################################
# Generate shell integration content
#######################################
generate_shell_integration() {
    local user_home
    user_home=$(get_remote_user_home)

    cat <<EOF
# ripgrep shell integration
# This file is sourced by ~/.shellrc.d/main.sh
# ripgrep is installed via devbox global, which is loaded by devbox-feature.sh

# Set ripgrep config path
export RIPGREP_CONFIG_PATH="${user_home}/.config/ripgrep/config"

# Track current ripgrep theme
export CURRENT_RG_THEME="${THEME}"

EOF

    # Add aliases if enabled
    if [ "$ENABLEALIASES" = "true" ]; then
        cat <<'EOF'
# Useful ripgrep aliases
alias rgi='rg --ignore-case'           # Case-insensitive search
alias rgf='rg --files'                 # List files (respects .gitignore)
alias rgh='rg --hidden'                # Include hidden files
alias rga='rg --hidden --no-ignore'    # Search all files (hidden + ignored)
alias rgc='rg --count'                 # Show match counts per file
alias rgl='rg --files-with-matches'    # List files with matches only

EOF
    fi

    # Add theme helper functions
    cat <<'EOF'
#######################################
# List available ripgrep themes
#######################################
rg-themes() {
    local themes_dir="/usr/local/share/devcontainer-features/ripgrep/themes"

    echo "Available ripgrep themes:"
    echo "  db2-dark   - DevOpsBuildingBlocks dark theme (default)"
    echo "  db2-light  - DevOpsBuildingBlocks light theme"
    echo "  none       - No theme (use terminal defaults)"
    echo ""
    echo "Current theme: ${CURRENT_RG_THEME:-unknown}"
    echo ""
    echo "Usage: rg-theme <theme-name>"
}

#######################################
# Switch ripgrep theme
# Updates ripgrep config file with new theme colors
#######################################
rg-theme() {
    if [ -z "$1" ]; then
        echo "Error: No theme specified"
        echo ""
        rg-themes
        return 1
    fi

    local theme="$1"
    local themes_dir="/usr/local/share/devcontainer-features/ripgrep/themes"
    local theme_file="${themes_dir}/${theme}.theme"
    local config_file="${RIPGREP_CONFIG_PATH:-${HOME}/.config/ripgrep/config}"
    local config_dir
    config_dir=$(dirname "$config_file")

    # Ensure config directory exists
    mkdir -p "$config_dir"

    # Handle "none" theme
    if [ "$theme" = "none" ]; then
        # Remove color settings from config, keep other options
        if [ -f "$config_file" ]; then
            grep -v "^--colors=" "$config_file" | grep -v "^# Theme:" > "${config_file}.tmp" || true
            mv "${config_file}.tmp" "$config_file"
        fi
        export CURRENT_RG_THEME="none"
        echo "ripgrep theme disabled (using terminal defaults)"
        return 0
    fi

    # Validate theme file exists
    if [ ! -f "$theme_file" ]; then
        echo "Error: Theme '$theme' not found"
        echo "Available themes:"
        find "$themes_dir" -name "*.theme" -exec basename {} .theme \; 2>/dev/null | sort | sed 's/^/  /'
        return 1
    fi

    # Remove existing color settings from config
    if [ -f "$config_file" ]; then
        grep -v "^--colors=" "$config_file" | grep -v "^# Theme:" > "${config_file}.tmp" || true
        mv "${config_file}.tmp" "$config_file"
    else
        # Create new config with smart-case
        echo "# ripgrep configuration
--smart-case" > "$config_file"
    fi

    # Add new theme colors
    echo "" >> "$config_file"
    echo "# Theme: ${theme}" >> "$config_file"
    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^#.*$ ]] && continue
        [[ -z "$line" ]] && continue
        echo "--colors=$line" >> "$config_file"
    done < "$theme_file"

    export CURRENT_RG_THEME="$theme"
    echo "Switched ripgrep theme to: $theme"
}
EOF
}

#######################################
# Set up shell integration for ripgrep
#######################################
setup_shell_integration() {
    log_info "Setting up shell integration"

    local shellrc_content
    shellrc_content=$(generate_shell_integration)

    write_shellrc_feature "ripgrep" "$shellrc_content"
}

#######################################
# Main installation function
#######################################
main() {
    log_info "Starting ripgrep installation"

    install_ripgrep
    setup_themes
    setup_config
    setup_shell_integration

    log_success "ripgrep feature installation complete"
}

# Execute main function
main "$@"
